spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/capstone?createDatabaseIfNotExist=true"
    username: root
    password: Abhishek@123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      password: Abhishek@123
      name: Abhishek


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082


info:
  app:
    name: "gatewayserver"
    description: "Property Gateway Server Application"
    version: "1.0.0"

userService:
  application:
    message: "Welcome the the user Service!! You can perform the basic sanity on this application like Searching, finding location of movies"

